from .customer import Customer
from .onsale import OnSale
from .allproducts import AllProducts
from .category import Category
from .contact import Contact
from .cart import Cart
from .checkout import Checkout
from .home import WhyChooseUs
from .home import Slider