# Generated by Django 4.0 on 2022-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_offer', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='uploads/products/')),
            ],
        ),
    ]
