# Generated by Django 4.0 on 2022-01-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_onsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.IntegerField()),
                ('product_offer', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='uploads/allproducts/')),
            ],
        ),
        migrations.AlterField(
            model_name='onsale',
            name='product_image',
            field=models.ImageField(upload_to='uploads/onsale/'),
        ),
    ]
