# Generated by Django 4.0 on 2022-01-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_allproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='product_brand',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allproducts',
            name='product_description',
            field=models.TextField(default=''),
        ),
    ]
