# Generated by Django 4.0 on 2022-02-18 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='onsale',
            name='product_name',
        ),
        migrations.AddField(
            model_name='onsale',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.allproducts'),
            preserve_default=False,
        ),
    ]
