# Generated by Django 4.0 on 2022-02-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_onsale_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_name', models.CharField(max_length=500)),
                ('icon_image', models.ImageField(upload_to='uploads/home/')),
                ('description', models.TextField(default='description')),
            ],
        ),
    ]
