# Generated by Django 4.0 on 2022-02-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='product_offer',
        ),
        migrations.RemoveField(
            model_name='onsale',
            name='product_price',
        ),
        migrations.AddField(
            model_name='onsale',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
    ]
