# Generated by Django 4.0 on 2022-02-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_onsale_product_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onsale',
            name='category',
        ),
    ]
